org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
loader_version_range=[1,)

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

mod_id=villager_news_addon_port
mod_name=Villager News Addon Port
mod_license=All Rights Reserved
mod_version=1.3.4-neoforge-1.21.1-randomized
mod_group_id=com.vnap

dialogue_test_command=false
emf_version=szv0UmJn
etf_version=XEJeKpgJ

esf_version=eafVUs7O
