modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="assets/villager-news-addon-port/icon.png"
authors="Oreville Studios Ltd, Element Animation, Java port assembled by marcy"
description='''
A Java Edition port of Villager News with contextual dialogue and EMF, ETF, and ESF models, textures, and sounds.
'''

[[mixins]]
config="villager-news-addon-port.mixins.json"

[[mixins]]
config="villager-news-addon-port.client.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="entity_model_features"
type="required"
versionRange="[3.0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="entity_texture_features"
type="required"
versionRange="[7.0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="entity_sound_features"
type="required"
versionRange="[0.8,)"
ordering="AFTER"
side="CLIENT"
